import type { ClubEvent, NewsArticle, AGMDocument, MemberProfile, Venue } from "@/types";

// ─── Venues ──────────────────────────────────────────────────────────────────
export const VENUES: Venue[] = [
  {
    id: "v-laelipa",
    name: "Centro Deportivo Municipal La Elipa",
    address: "C. del Alcalde Garrido Juaristi, 17, Moratalaz, 28030 Madrid",
    map_link: "https://maps.google.com/?q=Centro+Deportivo+Municipal+La+Elipa+Madrid",
    notes: "Madrid home ground. Training and junior cricket. Supported by Madrid City Council with 2 hours/week of subsidised access.",
    is_home: true,
  },
  {
    id: "v-sporting-alfaz",
    name: "Sporting Alfaz Cricket Ground",
    address: "Alfaz del Pi, Alicante, Spain",
    map_link: "https://maps.google.com/?q=Sporting+Alfaz+del+Pi+cricket",
    notes: "Home ground for 40-over and 20-over coastal league fixtures. ~460km from Madrid (4.5h drive).",
    is_home: false,
  },
  {
    id: "v-la-manga",
    name: "La Manga Club",
    address: "La Manga del Mar Menor, Murcia, Spain",
    map_link: "https://maps.google.com/?q=La+Manga+Club+Murcia",
    notes: "Venue for ECCL coastal league and Barcelona fixtures.",
    is_home: false,
  },
  {
    id: "v-barcelona",
    name: "Barcelona International CC",
    address: "Barcelona, Spain",
    map_link: "https://maps.google.com/?q=Barcelona+cricket",
    notes: "",
    is_home: false,
  },
];

// ─── Real Results (from ECCL scorecards & @madridcricketclub) ────────────────
export const EVENTS: ClubEvent[] = [
  // ── Upcoming fixtures ───────────────────────────────────────────────────────
  {
    id: "e-u18-menorca",
    type: "match",
    title: "Spanish Under-18 Championship",
    competition: "Cricket España — Junior",
    date: "2026-08-28",
    start_time: "09:00",
    meet_time: "08:00",
    venue_id: "v-la-manga",
    venue: VENUES[2],
    is_home: false,
    format: "t20",
    squad_size: 14,
    availability_deadline: "2026-08-22",
    late_changes_blocked: false,
    team: "juniors",
    notes: "Full weekend tournament (Fri–Sun 28–30 Aug). Menorca Cricket Club, Biniparrell, Illes Balears.",
    status: "scheduled",
  },
  {
    id: "e-barca-lamanga-t20-1",
    type: "match",
    title: "MCC vs Barcelona International CC — T20 (1)",
    opponent: "Barcelona International CC",
    competition: "ECCL T20 2026",
    date: "2026-09-05",
    start_time: "10:00",
    meet_time: "08:30",
    venue_id: "v-la-manga",
    venue: VENUES[2],
    is_home: false,
    format: "t20",
    squad_size: 12,
    availability_deadline: "2026-08-29",
    late_changes_blocked: false,
    team: "seniors",
    notes: "Weekend trip to La Manga (5–6 Sep). 2× T20 + 1× 40-overs vs Barcelona International CC.",
    status: "completed",
    result: {
      id: "r-barca-t20-1",
      event_id: "e-barca-lamanga-t20-1",
      our_score: "194/5",
      opposition_score: "112/8",
      overs: "20/14.3",
      result: "won",
      margin: "82 runs",
      summary: "Imran Siddque blazed a stunning 61 off 30 balls (5×4, 5×6) to power MCC to 194/5. Barcelona were bowled out for 112 in 14.3 overs. Adnan Shakib and Deepak Kumar Lamba each took 2 wickets. MCC won by 82 runs.",
    },
  },
  {
    id: "e-barca-lamanga-t20-2",
    type: "match",
    title: "MCC vs Barcelona International CC — T20 (2)",
    opponent: "Barcelona International CC",
    competition: "ECCL T20 2026",
    date: "2026-09-05",
    start_time: "14:00",
    meet_time: "13:30",
    venue_id: "v-la-manga",
    venue: VENUES[2],
    is_home: false,
    format: "t20",
    squad_size: 12,
    availability_deadline: "2026-08-29",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-barca-t20-2",
      event_id: "e-barca-lamanga-t20-2",
      our_score: "229/6",
      opposition_score: "156/8",
      overs: "20/20",
      result: "won",
      margin: "73 runs",
      cricclubs_link: "https://cricclubs.com/CricketEspana/fullScorecard.do?matchId=722&clubId=13753",
      summary: "Madrid Cricket Club posted a mammoth 229/6 — Imran Siddque blazing 62 off 34 (5×4, 5×6) and Gourav Saha retiring on 54. Jon Woodward then took 3 wickets to dismantle Barcelona, who were restricted to 156/8 chasing 230. MCC won by 73 runs to complete a dominant T20 double-header sweep.",
    },
    scorecard: {
      id: "sc-barca-t20-2",
      event_id: "e-barca-lamanga-t20-2",
      images: [],
      cricclubs_link: "https://cricclubs.com/CricketEspana/fullScorecard.do?matchId=722&clubId=13753",
      structured: {
        innings: [
          {
            team_name: "Madrid Cricket Club",
            total_runs: 229,
            total_wickets: 6,
            total_overs: "20",
            extras: { wides: 37, no_balls: 4, byes: 0, leg_byes: 0, penalty: 0, total: 43 },
            batting: [
              { name: "Sumon Hossain",   how_out: "caught", fielder: "A Shindore", bowler: "S Sathyashankar", runs: 28, balls: 19, fours: 4, sixes: 2, strike_rate: 147.37 },
              { name: "Utkarsh Bhatt",   how_out: "caught", fielder: "R Kranti",   bowler: "S Bhosale",       runs: 34, balls: 25, fours: 5, sixes: 1, strike_rate: 136.00 },
              { name: "Revat Naidoo",    how_out: "caught", fielder: "†U Razi",    bowler: "S Sathyashankar",runs: 0,  balls: 1,  fours: 0, sixes: 0, strike_rate: 0.00   },
              { name: "Gourav Saha",     how_out: "Retired Out",                                              runs: 54, balls: 33, fours: 7, sixes: 2, strike_rate: 163.64 },
              { name: "Imran Siddque",   how_out: "c&b",                            bowler: "R Kranti",       runs: 62, balls: 34, fours: 5, sixes: 5, strike_rate: 182.35 },
              { name: "Jon Woodward",    how_out: "run out", fielder: "R Kranti",                              runs: 0,  balls: 4,  fours: 0, sixes: 0, strike_rate: 0.00   },
              { name: "Anand Kaul",      how_out: "not out",                                                   runs: 2,  balls: 2,  fours: 0, sixes: 0, strike_rate: 100.00 },
              { name: "Prabin Bensam",   how_out: "not out",                                                   runs: 6,  balls: 4,  fours: 1, sixes: 0, strike_rate: 150.00 },
            ],
            bowling: [
              { name: "Shriram Bhosale",      overs: 4, maidens: 0, runs: 47, wickets: 1, economy: 11.75, wides: 2,  no_balls: 0 },
              { name: "Saurabh Sathyashankar",overs: 4, maidens: 0, runs: 33, wickets: 2, economy: 8.25,  wides: 9,  no_balls: 0 },
              { name: "Ram Kranti",            overs: 3, maidens: 0, runs: 34, wickets: 1, economy: 11.33, wides: 8,  no_balls: 0 },
              { name: "Antriksh Kanwar",       overs: 3, maidens: 0, runs: 30, wickets: 0, economy: 10.00, wides: 2,  no_balls: 0 },
              { name: "Umer Razi",             overs: 2, maidens: 0, runs: 18, wickets: 0, economy: 9.00,  wides: 4,  no_balls: 2 },
              { name: "Anish Shindore",        overs: 4, maidens: 0, runs: 65, wickets: 0, economy: 16.25, wides: 12, no_balls: 2 },
            ],
            fall_of_wickets: [
              { wicket: 1, score: 61,  overs: "5.5"  },
              { wicket: 2, score: 61,  overs: "5.6"  },
              { wicket: 3, score: 87,  overs: "8.2"  },
              { wicket: 4, score: 219, overs: "18.2" },
              { wicket: 5, score: 219, overs: "18.6" },
              { wicket: 6, score: 219, overs: "19.1" },
            ],
          },
          {
            team_name: "Barcelona International Cricket Club",
            total_runs: 156,
            total_wickets: 8,
            total_overs: "20",
            extras: { wides: 18, no_balls: 2, byes: 0, leg_byes: 2, penalty: 0, total: 22 },
            batting: [
              { name: "Ram Kranti",          how_out: "bowled",  bowler: "D Kumar Lamba",                    runs: 57, balls: 30, fours: 5, sixes: 5, strike_rate: 190.00 },
              { name: "Vrishab Kandral",     how_out: "caught",  fielder: "P Bensam",  bowler: "D Kumar Lamba",runs: 20, balls: 17, fours: 3, sixes: 0, strike_rate: 117.65 },
              { name: "Umer Razi",           how_out: "caught",  fielder: "G Saha",    bowler: "S Hossain",   runs: 14, balls: 17, fours: 1, sixes: 1, strike_rate: 82.35  },
              { name: "Charudath Raghavan",  how_out: "Retired Out",                                           runs: 4,  balls: 7,  fours: 0, sixes: 0, strike_rate: 57.14  },
              { name: "Shriram Bhosale",     how_out: "caught",  fielder: "D Kumar Lamba", bowler: "J Woodward",runs: 14, balls: 8,  fours: 1, sixes: 1, strike_rate: 175.00 },
              { name: "Antriksh Kanwar",     how_out: "stumped", fielder: "J Healey", bowler: "J Woodward",   runs: 9,  balls: 8,  fours: 1, sixes: 0, strike_rate: 112.50 },
              { name: "Aditya Pandita",      how_out: "not out",                                               runs: 8,  balls: 18, fours: 0, sixes: 0, strike_rate: 44.44  },
              { name: "Saurabh Sathyashankar",how_out: "run out", fielder: "J Woodward",                      runs: 0,  balls: 1,  fours: 0, sixes: 0, strike_rate: 0.00   },
              { name: "Omar Ashfaq",         how_out: "caught",  fielder: "P Bensam",  bowler: "J Woodward",  runs: 0,  balls: 2,  fours: 0, sixes: 0, strike_rate: 0.00   },
              { name: "Anish Shindore",      how_out: "not out",                                               runs: 8,  balls: 13, fours: 1, sixes: 0, strike_rate: 61.54  },
            ],
            bowling: [
              { name: "Adnan Shakib",       overs: 2, maidens: 0, runs: 17, wickets: 0, economy: 8.50, wides: 2, no_balls: 0 },
              { name: "Deepak Kumar Lamba", overs: 4, maidens: 0, runs: 34, wickets: 2, economy: 8.50, wides: 2, no_balls: 0 },
              { name: "Imran Siddque",      overs: 1, maidens: 0, runs: 19, wickets: 0, economy: 19.00,wides: 0, no_balls: 0 },
              { name: "Abdul Hakeem",       overs: 4, maidens: 0, runs: 37, wickets: 0, economy: 9.25, wides: 8, no_balls: 0 },
              { name: "Sumon Hossain",      overs: 3, maidens: 0, runs: 22, wickets: 1, economy: 7.33, wides: 2, no_balls: 2 },
              { name: "Jon Woodward",       overs: 3, maidens: 0, runs: 16, wickets: 3, economy: 5.33, wides: 0, no_balls: 0 },
              { name: "Anand Kaul",         overs: 2, maidens: 0, runs: 7,  wickets: 0, economy: 3.50, wides: 4, no_balls: 0 },
              { name: "Utkarsh Bhatt",      overs: 1, maidens: 0, runs: 2,  wickets: 0, economy: 2.00, wides: 0, no_balls: 0 },
            ],
            fall_of_wickets: [
              { wicket: 1, score: 76,  overs: "6.4"  },
              { wicket: 2, score: 93,  overs: "8.5"  },
              { wicket: 3, score: 108, overs: "11.1" },
              { wicket: 4, score: 120, overs: "12.2" },
              { wicket: 5, score: 130, overs: "13.3" },
              { wicket: 6, score: 139, overs: "15.1" },
              { wicket: 7, score: 139, overs: "15.2" },
              { wicket: 8, score: 139, overs: "15.4" },
            ],
          },
        ],
      },
    },
  },
  {
    id: "e-barca-lamanga-40",
    type: "match",
    title: "MCC vs Barcelona International CC — 40 Overs",
    opponent: "Barcelona International CC",
    competition: "ECCL 40 Overs 2026",
    date: "2026-09-06",
    start_time: "10:00",
    meet_time: "08:30",
    venue_id: "v-la-manga",
    venue: VENUES[2],
    is_home: false,
    format: "40_over",
    squad_size: 12,
    availability_deadline: "2026-08-29",
    late_changes_blocked: false,
    team: "seniors",
    status: "scheduled",
  },
  {
    id: "e-net-6sep",
    type: "nets",
    title: "Senior Net Practice",
    date: "2026-09-06",
    start_time: "10:00",
    meet_time: "09:45",
    venue_id: "v-laelipa",
    venue: VENUES[0],
    is_home: true,
    squad_size: 20,
    late_changes_blocked: false,
    team: "seniors",
    notes: "10am–1pm.",
    status: "scheduled",
  },
  {
    id: "e-junior-18sep",
    type: "nets",
    title: "Junior Cricket",
    date: "2026-09-18",
    start_time: "18:00",
    meet_time: "17:45",
    venue_id: "v-laelipa",
    venue: VENUES[0],
    is_home: true,
    squad_size: 20,
    late_changes_blocked: false,
    team: "juniors",
    notes: "6pm–8pm at La Elipa.",
    status: "scheduled",
  },
  {
    id: "e-net-20sep",
    type: "nets",
    title: "Senior Net Practice",
    date: "2026-09-20",
    start_time: "10:00",
    meet_time: "09:45",
    venue_id: "v-laelipa",
    venue: VENUES[0],
    is_home: true,
    squad_size: 20,
    late_changes_blocked: false,
    team: "seniors",
    notes: "10am–1pm.",
    status: "scheduled",
  },
  {
    id: "e-ecs-oct",
    type: "match",
    title: "ECS T10 Madrid — Tournament Day 1",
    competition: "European Cricket Series T10 Madrid",
    date: "2026-10-19",
    start_time: "08:30",
    meet_time: "07:30",
    venue_id: "v-laelipa",
    venue: VENUES[0],
    is_home: true,
    format: "t10",
    squad_size: 12,
    availability_deadline: "2026-10-10",
    late_changes_blocked: false,
    team: "seniors",
    notes: "ECS T10 in Madrid. MCC + 4 other teams (TBC). Games 08:30–17:00. All games streamed live on ECN channels. Players must be happy to be recorded. Arrive 07:30–08:00 to set up. Player availability will be requested closer to the time.",
    status: "scheduled",
  },
  {
    id: "e-madrid-20over-oct",
    type: "match",
    title: "Madrid 20-Over League",
    competition: "Madrid 20-Over League",
    date: "2026-10-01",
    start_time: "10:00",
    meet_time: "09:30",
    venue_id: "v-laelipa",
    venue: VENUES[0],
    is_home: true,
    format: "t20",
    squad_size: 12,
    availability_deadline: "2026-09-25",
    late_changes_blocked: false,
    team: "seniors",
    notes: "Madrid 20-over league at La Elipa starting in October. Dates and opponents to be confirmed.",
    status: "scheduled",
  },

  // ── Real completed results (from ECCL scorecards) ───────────────────────────
  {
    id: "e-eccl40-jul19",
    type: "match",
    title: "MCC vs La Manga Torrevieja CC",
    opponent: "La Manga Torrevieja CC",
    competition: "ECCL 40 Overs 2026",
    date: "2026-07-19",
    start_time: "10:00",
    venue_id: "v-sporting-alfaz",
    venue: VENUES[1],
    is_home: false,
    format: "40_over",
    squad_size: 11,
    availability_deadline: "2026-07-14",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-eccl40-jul19",
      event_id: "e-eccl40-jul19",
      our_score: "272/10",
      opposition_score: "246/9",
      overs: "37.4/40",
      result: "won",
      margin: "26 runs",
      summary: "MCC posted 272 all out and defended it to win by 26 runs. A commanding performance.",
    },
  },
  {
    id: "e-eccl40-jun21",
    type: "match",
    title: "MCC vs Sporting Alfas CC",
    opponent: "Sporting Alfas Cricket Club",
    competition: "ECCL 40 Overs 2026",
    date: "2026-06-21",
    start_time: "10:00",
    venue_id: "v-sporting-alfaz",
    venue: VENUES[1],
    is_home: false,
    format: "40_over",
    squad_size: 11,
    availability_deadline: "2026-06-16",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-eccl40-jun21",
      event_id: "e-eccl40-jun21",
      our_score: "246/10",
      opposition_score: "247/2",
      overs: "39/40",
      result: "lost",
      margin: "8 wickets",
      summary: "Sporting Alfas chased 246 with 8 wickets to spare in 26.2 overs.",
    },
  },
  {
    id: "e-t20-jun20-1",
    type: "match",
    title: "Sporting Alfas CC vs MCC — T20 (1)",
    opponent: "Sporting Alfas Cricket Club",
    competition: "ECCL T20 2026",
    date: "2026-06-20",
    start_time: "10:00",
    venue_id: "v-sporting-alfaz",
    venue: VENUES[1],
    is_home: false,
    format: "t20",
    squad_size: 11,
    availability_deadline: "2026-06-14",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-t20-jun20-1",
      event_id: "e-t20-jun20-1",
      our_score: "191/9",
      opposition_score: "252/4",
      overs: "20/20",
      result: "lost",
      margin: "61 runs",
      summary: "Sporting Alfas posted 252/4 and restricted MCC to 191/9.",
    },
  },
  {
    id: "e-t20-jun20-2",
    type: "match",
    title: "Sporting Alfas CC vs MCC — T20 (2)",
    opponent: "Sporting Alfas Cricket Club",
    competition: "ECCL T20 2026",
    date: "2026-06-20",
    start_time: "14:00",
    venue_id: "v-sporting-alfaz",
    venue: VENUES[1],
    is_home: false,
    format: "t20",
    squad_size: 11,
    availability_deadline: "2026-06-14",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-t20-jun20-2",
      event_id: "e-t20-jun20-2",
      our_score: "137/6",
      opposition_score: "178/4",
      overs: "20/20",
      result: "lost",
      margin: "41 runs",
      summary: "Sporting Alfas won the second T20 by 41 runs.",
    },
  },
  {
    id: "e-t20-may30-1",
    type: "match",
    title: "La Manga Torrevieja CC vs MCC — T20 (1)",
    opponent: "La Manga Torrevieja CC",
    competition: "ECCL T20 2026",
    date: "2026-05-30",
    start_time: "10:00",
    venue_id: "v-la-manga",
    venue: VENUES[2],
    is_home: false,
    format: "t20",
    squad_size: 11,
    availability_deadline: "2026-05-24",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-t20-may30-1",
      event_id: "e-t20-may30-1",
      our_score: "148/10",
      opposition_score: "214/1",
      overs: "20/20",
      result: "lost",
      margin: "66 runs",
    },
  },
  {
    id: "e-t20-may30-2",
    type: "match",
    title: "MCC vs La Manga Torrevieja CC — T20 (2)",
    opponent: "La Manga Torrevieja CC",
    competition: "ECCL T20 2026",
    date: "2026-05-30",
    start_time: "14:00",
    venue_id: "v-la-manga",
    venue: VENUES[2],
    is_home: false,
    format: "t20",
    squad_size: 11,
    availability_deadline: "2026-05-24",
    late_changes_blocked: false,
    team: "seniors",
    status: "completed",
    result: {
      id: "r-t20-may30-2",
      event_id: "e-t20-may30-2",
      our_score: "216/8",
      opposition_score: "144/6",
      overs: "20/20",
      result: "won",
      margin: "72 runs",
      summary: "MCC bounced back in the second T20 to win by 72 runs.",
    },
  },
];

// ─── News ─────────────────────────────────────────────────────────────────────
export const NEWS: NewsArticle[] = [
  {
    id: "n-25th",
    slug: "mcc-25th-anniversary-2026",
    title: "Happy 25th Anniversary, Madrid Cricket Club!",
    excerpt: "Twenty-five years ago, Madrid Cricket Club was reborn from a simple idea shared over a beer. Today we celebrate a quarter-century of cricket, friendship, and community.",
    content: `Twenty-five years ago, Madrid Cricket Club was reborn from a simple idea. What started with a classified ad in a free English-language newspaper — "Se buscan jugadores de críquet" — that received just three responses, has grown into one of Spain's most enduring cricket clubs.\n\nToday MCC has over 100 members and fields men's, women's, and junior teams across multiple competitions.`,
    hero_image_url: "/images/real/mcc-1982.png",
    author_name: "Club Committee",
    published_at: "2026-07-23T10:00:00Z",
    tags: ["anniversary", "club-history"],
    is_match_report: false,
  },
  {
    id: "n-elpais",
    slug: "elpais-feature-august-2026",
    title: "El País Feature: MCC — An Institution Without a Home Ground",
    excerpt: "Spain's national newspaper El País featured Madrid Cricket Club in a detailed piece about the club's 25-year history, its exile to the Alicante coast for league cricket, and the rise of cricket in Spain.",
    content: `Madrid Cricket Club featured in El País in August 2026 in a piece titled "Una institución con solera pero sin sede, exiliado en la costa alicantina."\n\nRead the full article at elpais.com.`,
    hero_image_url: "/images/real/mcc-team-alicante.jpg",
    author_name: "El País",
    published_at: "2026-08-09T08:00:00Z",
    tags: ["press", "feature", "el-pais"],
    is_match_report: false,
  },
  {
    id: "n-eccl-jul19",
    slug: "eccl-40-overs-win-la-manga-july-2026",
    title: "MCC Win ECCL 40-Overs — 272 All Out, Won by 26 Runs",
    excerpt: "Madrid Cricket Club posted 272 all out and defended it to beat La Manga Torrevieja CC by 26 runs in the ECCL 40 Overs league.",
    content: `MCC batted first and posted 272/10 in 37.4 overs. La Manga Torrevieja CC replied with 246/9 in 35.4 overs — Madrid won by 26 runs.`,
    hero_image_url: "/images/real/mcc-la-manga-pro.jpg",
    author_name: "Club Secretary",
    published_at: "2026-07-19T18:00:00Z",
    tags: ["match-report", "eccl", "win"],
    related_fixture_id: "e-eccl40-jul19",
    is_match_report: true,
  },
  {
    id: "n-fathers-sprogs",
    slug: "fathers-sprogs-england-tour-july-2026",
    title: "Fathers & Sprogs Tour England — Two Wins at Blockley CC",
    excerpt: "A successful weekend in England — Madrid CC's Fathers and Sprogs side beat Blockley Cricket Club twice.",
    content: `Madrid CC Fathers and Sprogs travelled to Blockley Cricket Club in the Cotswolds and won both matches. A weekend to remember.`,
    hero_image_url: "/images/real/mcc-ecn-lineup.jpg",

    author_name: "Club Secretary",
    published_at: "2026-07-20T18:00:00Z",
    tags: ["tour", "england", "win"],
    is_match_report: true,
  },
];

// ─── AGM Documents ────────────────────────────────────────────────────────────
export const AGM_DOCS: AGMDocument[] = [
  {
    id: "agm1",
    year: 2026,
    title: "AGM 2026 — Minutes",
    document_url: "/documents/agm-2026-minutes.pdf",
    type: "minutes",
    is_public: true,
    uploaded_at: "2026-03-15T12:00:00Z",
  },
  {
    id: "agm2",
    year: 2026,
    title: "AGM 2026 — Annual Accounts",
    document_url: "/documents/agm-2026-accounts.pdf",
    type: "accounts",
    is_public: true,
    uploaded_at: "2026-03-15T12:00:00Z",
  },
];

// ─── Season Stats ─────────────────────────────────────────────────────────────
export const SEASON_STATS = {
  played: 8,
  won: 4,
  lost: 4,
  drew: 0,
  nrr: "+0.12",
  season: "2026",
};

// ─── Committee (REAL — corrected Aug 2026) ───────────────────────────────────
export const COMMITTEE = [
  {
    role: "President",
    name: "Jon Woodward",
    email: "jonwoodward1975@gmail.com",
    phone: "+34 655 069 911",
    bio: "One of MCC's founding members, Jon has been a cornerstone of cricket in Madrid for over 30 years. As President, he sets the direction for the club and ensures it continues to grow in the right way, but his influence extends well beyond the committee room. Jon is deeply embedded in the Cricket Espana ecosystem, working at a national level to help shape the game's development across the country.",
  },
  {
    role: "Vice President",
    name: "Lewis Clarke",
    email: "mail@lewclark.com",
    phone: "+34 687 424 539",
    bio: "As Vice President, Lewis is the driving force behind MCC's growth beyond the senior game. He leads the club's Juniors setup, personally organising and running the Youth programme that has brought a new generation of cricketers through the ranks in Madrid. Alongside that, he plays a central role in developing and supporting Women's cricket at the club, helping to make MCC one of the most inclusive cricket communities in Spain.",
  },
  {
    role: "Treasurer",
    name: "Adam Langhans",
    bio: "Handles club finances, match fees, and budgeting for tours and equipment.",
  },
  {
    role: "Secretary",
    name: "Victor Medina",
    bio: "Victor is the engine room of MCC's day-to-day operations. As Club Secretary, he handles the lion's share of the club's administration: managing correspondence, coordinating with Cricket Espana, keeping player records in order and making sure everything behind the scenes runs without a hitch. If something needs doing, Victor has almost certainly already done it.",
  },
  {
    role: "Captain (40-over)",
    name: "Anand Kaul",
    bio: "Leads the side in ECCL 40-over competition.",
  },
  {
    role: "Captain (20-over)",
    name: "Gourav Saha",
    bio: "Leads the side in T20 and the new Madrid 20-over league.",
  },
];
